# Generated by Django 3.1.7 on 2021-03-16 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_brand', models.CharField(max_length=255)),
                ('watch_model', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('watch_price', models.PositiveIntegerField()),
            ],
        ),
    ]
